version: '3.8'

services:
  markdown-pdf-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - COMPANY_NAME=Your Company Name
      - MAX_FILE_SIZE=52428800
      - MAX_EXTRACTED_SIZE=209715200
      - UPLOAD_TIMEOUT=300
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - markdown-pdf-api
    restart: unless-stopped
    profiles:
      - production