version: '3.8'

services:
  api:
    build: .
    container_name: markdown-pdf-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - COMPANY_NAME=Your Company Name
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: markdown-pdf-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped

networks:
  default:
    name: markdown-pdf-network